# 统计函数

In [11]:
import numpy as np
# arr1 = np.random.randint(1, 5, (2, 3))
# print(arr1)
# print(np.mean(arr1))
# print(np.sum(arr1))
# print(np.max(arr1))
# print(np.min(arr1))
# arr1 = np.arange(5)
# print(arr1)
# print(np.std(arr1))
# print(np.var(arr1))
# print(np.argmax(arr1))
# print(np.argmin(arr1))
arr1 = np.array([[1, 2],[ 3, 4]])
arr1
# print(np.cumsum(arr1))
print(np.cumprod(arr1))
print("---------")
print(np.cumprod(arr1,axis=0))
print("---------")
print(np.cumprod(arr1, axis=1))


[ 1  2  6 24]
---------
[[1 2]
 [3 8]]
---------
[[ 1  2]
 [ 3 12]]


# 比较函数

In [13]:
arr1 = np.array([1, 2, 3, 4, 5])
# print(np.any(arr1 > 3))
print(np.all(arr1 > 3))


False


# 排序函数

In [21]:
# arr1 = np.random.randint(0, 10, (3, 3))
# print(arr1)
# print("~~~~~~~~~")
# arr1.sort()
# print(arr1)
# arr1.sort(axis=0)
# print(arr1)

arr1 = np.random.randint(0, 10, (3, 3))
print(arr1)
print(np.sort(arr1,axis=1))


[[9 7 6]
 [3 7 9]
 [5 3 9]]
[[6 7 9]
 [3 7 9]
 [3 5 9]]


# 去重函数

In [22]:
arr1 = np.random.randint(0, 5, (3, 3))
print(arr1)
print(np.unique(arr1))


[[1 2 2]
 [2 1 4]
 [3 2 3]]
[1 2 3 4]


# 基本运算

In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# 数组和标量元素进行运算

In [26]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1 + 100)
print(arr1 - 100)
print(arr1 * 100)
print(arr1 / 100)


[[101 102 103]
 [104 105 106]]
[[-99 -98 -97]
 [-96 -95 -94]]
[[100 200 300]
 [400 500 600]]
[[0.01 0.02 0.03]
 [0.04 0.05 0.06]]


# 广播机制

In [31]:
import numpy as np
# 一维数组
arr1 = np.array([1, 2, 3])  # 形状为 (3,)==>(1,3)
# 二维数组
arr2 = np.array([[4], [5], [6]])  # 形状为 (3, 1)
# arr2
# 对 arr1 应用规则 1，在其形状最左边补 1，变为 (1, 3)  [[1,2,3]]
# 此时 arr1 形状 (1, 3) 和 arr2 形状 (3, 1) 满足广播条件
result = arr1 + arr2
print("规则 1 示例结果：\n", result)


规则 1 示例结果：
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [32]:
import numpy as np
# 一维数组
arr5 = np.array([1, 2, 3])  # 形状为 (3,)
# 一维数组
arr6 = np.array([4, 5])  # 形状为 (2,)
try:
    result = arr5 + arr6
    print(result)
except ValueError as e:
    print(f"规则 3 示例错误信息：{e}")


规则 3 示例错误信息：operands could not be broadcast together with shapes (3,) (2,) 


# 对位乘法

In [33]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])
print(arr1 * arr2)
print(np.multiply(arr1, arr2))


[[ 6 10 12]
 [12 10  6]]
[[ 6 10 12]
 [12 10  6]]


# 矩阵乘法

In [42]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5], [4, 3], [2, 1]])
#对于矩阵乘法来说，要求第一个矩阵的列数等于第二个矩阵的行数
arr2
# print(arr1)
# print(arr2)
# print(arr1.shape, arr2.shape)
# print(np.dot(arr1, arr2))
# print(arr1.dot(arr2))
# print(arr1 @ arr2)
# 一个二维数组跟一个大小合适的一维数组的矩阵点积运算之后将会得到一个一维数组
arr3 = np.array([6, 5, 4])
print(arr1 @ arr3)


[28 73]
