# 该案例演示了数组的创建方式

In [8]:
# array()：将输入数据转换为ndarray，会进行copy。
# asarray()：将输入数据转换为ndarray，如果输入本身是ndarray则不会进行copy。

import numpy as np
data = [1,2,3]
print(f"data的内存地址:{id(data)}")
# 通过列表创建数组对象
arr1 = np.array(data)
print(f"arr1的内存地址:{id(arr1)}")
print("===" * 20)

# 将输入数据转换为ndarray，会进行copy
arr2 = np.array(arr1)
print(f"arr2的内存地址:{id(arr2)}")
print("===" * 20)

arr3 = np.asarray(arr1)
print(arr3)
print(f"arr3的内存地址:{id(arr3)}")




data的内存地址:2007061846784
arr1的内存地址:2007061716720
arr2的内存地址:2007061716048
[1 2 3]
arr3的内存地址:2007061716720


In [16]:
# zeros()：      返回与给定形状和类型的新数组，用0填充。
# zeros_like()：返回与给定数组具有相同形状和类型的0新数组。
# ones()：返回给定形状和类型的新数组，用1填充。
# empty()：返回给定形状和类型的未初始化的新数组。

# ones_like()：返回与给定数组具有相同形状和类型的1新数组。
# empty_like()：返回与给定数组具有相同形状和类型的未初始化的新数组。

arr = np.zeros((2,3))
arr = np.ones((2,3))
arr = np.empty((2,4))

arr1 = np.zeros_like(arr)
arr1 = np.ones_like(arr)
arr1 = np.empty_like(arr)

arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# full()：返回给定形状和类型的新数组，用指定的值填充。
# full_like()：返回与给定数组具有相同形状和类型的用指定值填充的新数组。
arr1 = np.full((2, 3), 6)


arr2 = np.full_like(arr1, 5)
arr2


array([[5, 5, 5],
       [5, 5, 5]])

In [22]:
arr = np.arange(0,10,2)
print(arr.size)
print(arr.dtype)
arr

5
int64


array([0, 2, 4, 6, 8])

In [27]:
# linspace()：返回指定范围和元素个数的等差数列。数组元素类型为浮点型。
# logspace()：返回指定指数范围、元素个数、底数的等比数列。
# arr = np.linspace(0,10,5)
arr = np.linspace(0,10,5,endpoint=False)
arr3 = np.logspace(start=2, stop=5, num=4, base=2)
arr3



array([ 4.,  8., 16., 32.])

In [33]:
# random.rand()：返回给定形状的数组，用 [0, 1) 上均匀分布的随机样本填充。
# random.randint()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机整数填充。
# random.uniform()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机浮点数填充。
# random.randn()：返回给定形状的数组，用标准正态分布(均值为0，标准差为1)的随机样本填充。
arr1 = np.random.rand(2, 3)
arr1 = np.random.randint(low=0, high=10, size=(2, 3))
arr1 = np.random.uniform(low=0, high=10, size=(2, 3))
arr1 = np.random.randn(2, 3)
arr1


array([[-0.5700395 , -0.89316284,  0.97006712],
       [-1.17089494, -0.18253116,  1.20505663]])

In [35]:
# matrix为ndarray的子类，只能生成二维的矩阵
# my_m = np.matrix("1,2;3,4")
my_m = np.matrix([[1,2],[3,4]])
my_m

matrix([[1, 2],
        [3, 4]])

In [43]:
arr1 = np.array([1,2,3],dtype=np.float64)
# print(arr1)

# arr2 = np.array([0.2, 2.5, 4.8], dtype="i8")
arr3 = arr1.astype(dtype=np.int64)
# arr3

[1. 2. 3.]
