# 该案例演示了ndarray的切片和索引

In [6]:
import numpy as np
arr = np.arange(10)
print(arr)

#获取索引为2的数据
print(arr[2])
# 从索引2开始到索引9(不包含)停止，间隔为2
print(arr[2:9:2])
# 从索引2开始到索引9(不包含)停止，间隔为2
print(arr[slice(2, 9, 2)])
# 从索引2开始到最后(不包含)，默认间隔为1
print(arr[2:])
# 从索引2开始到索引9(不包含)结束，默认间隔为1
print(arr[2:9])


[0 1 2 3 4 5 6 7 8 9]
2
[2 4 6 8]
[2 4 6 8]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]


In [18]:
# arr1 = np.random.randn(2, 3)
arr1 = np.array([[1.5, 2.3], [-3.2, 4.8]])
# np.abs()	元素的绝对值，参数是 number 或 array
# np.abs(arr1)

# np.ceil()	向上取整，参数是 number 或 array
# np.ceil(arr1)
# np.floor()	向下取整，参数是 number 或 array
# np.floor(arr1)
# np.rint()	四舍五入，参数是 number 或 array
# np.rint(arr1)
# np.isnan()	判断元素是否为NaN(Not a Number) ，参数是 number 或 array
# np.isnan(arr1)
# np.multiply()	元素相乘，参数是 number 或 array。如果第二个参数传递的是number，原数组中所有元素乘以这个数字，返回新的数组；如果第二个参数也是一个数组，是将两个数组中对应位置的元素相乘，返回一个新的数组，其形状与输入数组相同。
arr1 = np.array([[1, 2], [3, 4]])
# np.multiply(arr1, arr1)

# np.divide()	元素相除，参数是 number 或 array
# np.divide(arr1, 2)
# np.where(condition, x, y)	三元运算符，x if condition else y
np.where(arr1 > 2,66,55)



array([[55, 55],
       [66, 66]])